### ISSUE TITLE
UINT16 image support

### ISSUE THREAD

**Issue by rqi14** [seikichi/tiff.js#34]
Hi. I tried the demo with an uint16 grey scale image and it crashed. 

tiff.min.js:102 Uncaught abort({}) at Error
    at wf (http://seikichi.github.io/tiff.js/tiff.min.js:89:367)
    at Vc (http://seikichi.github.io/tiff.js/tiff.min.js:101:412)
    at ___syscall192 (http://seikichi.github.io/tiff.js/tiff.min.js:1066:155)
    at Li (http://seikichi.github.io/tiff.js/tiff.min.js:1575:41)
    at Array.Aa (http://seikichi.github.io/tiff.js/tiff.min.js:1981:431)
    at rd (http://seikichi.github.io/tiff.js/tiff.min.js:1146:252)
    at _TIFFOpen (http://seikichi.github.io/tiff.js/tiff.min.js:3166:490)
    at Object.Yh [as ccall] (http://seikichi.github.io/tiff.js/tiff.min.js:112:19)
    at new Lb (http://seikichi.github.io/tiff.js/tiff.min.js:3183:87)
    at FileReader.<anonymous> (http://seikichi.github.io/tiff.js/upload.html:47:20)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by rqi14** [comment]
Sorry it's just the image is too large
