### ISSUE TITLE
RangeError: offset is out of bounds

### ISSUE THREAD

**Issue by ltinerary** [seikichi/tiff.js#61]
when i load a *.tif file,I got an error:
```bash
RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at Object.mmap (tiff.min.js?e97c:950)
    at Object.mmap (tiff.min.js?e97c:999)
    at ___syscall192 (tiff.min.js?e97c:1065)
    at Li (tiff.min.js?e97c:1575)
    at Array.Aa (tiff.min.js?e97c:1981)
    at rd (tiff.min.js?e97c:1146)
    at _TIFFOpen (tiff.min.js?e97c:3166)
    at Object.Yh [as ccall] (tiff.min.js?e97c:112)
    at new Lb (tiff.min.js?e97c:3183)
tiff.min.js?e97c:105 RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at Object.mmap (tiff.min.js?e97c:950)
    at Object.mmap (tiff.min.js?e97c:999)
    at ___syscall192 (tiff.min.js?e97c:1065)
    at Li (tiff.min.js?e97c:1575)
    at Array.Aa (tiff.min.js?e97c:1981)
    at rd (tiff.min.js?e97c:1146)
    at _TIFFOpen (tiff.min.js?e97c:3166)
    at Object.Yh [as ccall] (tiff.min.js?e97c:112)
    at new Lb (tiff.min.js?e97c:3183)
tiff.min.js?e97c:102 Uncaught abort({}) at Error
    at wf (webpack-internal:///./node_modules/tiff.js/tiff.min.js:89:367)
    at Vc (webpack-internal:///./node_modules/tiff.js/tiff.min.js:101:412)
    at ___syscall192 (webpack-internal:///./node_modules/tiff.js/tiff.min.js:1066:155)
    at Li (webpack-internal:///./node_modules/tiff.js/tiff.min.js:1575:41)
    at Array.Aa (webpack-internal:///./node_modules/tiff.js/tiff.min.js:1981:431)
    at rd (webpack-internal:///./node_modules/tiff.js/tiff.min.js:1146:252)
    at _TIFFOpen (webpack-internal:///./node_modules/tiff.js/tiff.min.js:3166:490)
    at Object.Yh [as ccall] (webpack-internal:///./node_modules/tiff.js/tiff.min.js:112:19)
    at new Lb (webpack-internal:///./node_modules/tiff.js/tiff.min.js:3183:87)
    at XMLHttpRequest.xhr.onload (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/HelloWorld.vue?vue&type=script&lang=js&:120:18)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```
 May be my .tif file is too large?[145 MB (152,116,673 字节)]

**Comment by ltinerary** [comment]
```js
  Tiff.initialize({TOTAL_MEMORY: 19777216 * 10});
```
can be work!

**Comment by accwill** [comment]
@ltinerary 

> ```js
>   Tiff.initialize({TOTAL_MEMORY: 19777216 * 10});
> ```
> 
> can be work!
Thank you.
