### ISSUE TITLE
Continuous loading of 29 pictures and error reporting  'Uncaught abort({})'

### ISSUE THREAD

**Issue by delete1226** [seikichi/tiff.js#67]
when continuous loading of 29 pictures and error reporting 

Uncaught abort({}) at Error
at jsStackTrace (https://d62epjyi40fiq.cloudfront.net/cm/js/tiff.js:79:20924)
at stackTrace (https://d62epjyi40fiq.cloudfront.net/cm/js/tiff.js:79:21107)
at abort (https://d62epjyi40fiq.cloudfront.net/cm/js/tiff.js💯5646)
at ___syscall192 (https://d62epjyi40fiq.cloudfront.net/cm/js/tiff.js:79:528423)
at cq (https://d62epjyi40fiq.cloudfront.net/cm/js/tiff.js:89:65708)
at Array.xe (https://d62epjyi40fiq.cloudfront.net/cm/js/tiff.js:83:118776)
at pd (https://d62epjyi40fiq.cloudfront.net/cm/js/tiff.js:83:93033)
at le (https://d62epjyi40fiq.cloudfront.net/cm/js/tiff.js:83:117061)
at Object.ccallFunc [as ccall] (https://d62epjyi40fiq.cloudfront.net/cm/js/tiff.js:79:8204)
at new Tiff (https://d62epjyi40fiq.cloudfront.net/cm/js/tiff.js:301:37)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by xiaozhuai** [comment]
```
// Initialize the memory with 300 MB
// call this first
Tiff.initialize({TOTAL_MEMORY: 314572800}); 
```
